version: '3.9'

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql@15/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres